# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: exampleuser
      POSTGRES_PASSWORD: examplepass
      POSTGRES_DB: exampledb
    # Specify to enable access outside docker compose network?
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "5433:8080"